
import streamlit as st
import requests
import pandas as pd
import time
import json
import plotly.express as px

# Configuration
API_URL = "http://localhost:8000"

st.set_page_config(
    page_title="Agentic Portfolio Optimizer",
    page_icon="📈",
    layout="wide"
)

st.title("🤖 Agentic Portfolio Optimizer")
st.markdown("### AI-Powered Portfolio Customization")

# Sidebar for inputs
with st.sidebar:
    st.header("Investment Configuration")
    mandate = st.text_area(
        "Investment Mandate", 
        height=150,
        value="I want a high-growth portfolio focused on technology and renewable energy, avoiding fossil fuels.",
        help="Describe your investment goals, constraints, and preferences."
    )
    
    investment_amount = st.number_input(
        "Investment Amount ($)", 
        min_value=1000.0, 
        value=100000.0, 
        step=1000.0,
        format="%f"
    )
    
    start_button = st.button("🚀 Start Optimization", type="primary")

# Main Content Area
if "job_id" not in st.session_state:
    st.session_state.job_id = None
    st.session_state.job_status = None
    st.session_state.job_result = None

def start_analysis():
    try:
        payload = {
            "mandate": mandate,
            "investment_amount": float(investment_amount)
        }
        response = requests.post(f"{API_URL}/analyze", json=payload)
        response.raise_for_status()
        data = response.json()
        st.session_state.job_id = data["job_id"]
        st.session_state.job_status = "running"
        st.session_state.job_result = None
        st.rerun()
    except Exception as e:
        st.error(f"Failed to start analysis: {e}")

if start_button:
    start_analysis()

if st.session_state.job_id:
    # Polling Loop
    if st.session_state.job_status in ["running", "pending"]:
        with st.spinner("Agents are collaborating on your portfolio..."):
            time.sleep(2) # Poll every 2 seconds
            try:
                response = requests.get(f"{API_URL}/jobs/{st.session_state.job_id}")
                if response.status_code == 200:
                    job_data = response.json()
                    status = job_data.get("status")
                    
                    if status != st.session_state.job_status:
                        st.session_state.job_status = status
                        if status == "completed":
                            st.session_state.job_result = job_data.get("result", {})
                        elif status == "failed":
                            st.error(f"Job failed: {job_data.get('error')}")
                        st.rerun()
                    else:
                        # Continue polling if status hasn't changed
                        st.rerun()
            except Exception as e:
                st.warning(f"Connection error: {e}")

    # Display Results or Progress
    result = st.session_state.job_result
    
    if result:
        # 1. Review Console
        st.markdown("### 📝 Agent Review Console")
        st.info("Read the automated review and feedback generated by the agents below.")
        
        feedback_logs = result.get("feedback", [])
        feedback_text = "\n".join([f"- {msg}" for msg in feedback_logs]) if feedback_logs else "No feedback logs available."
        
        st.text_area(
            "Agent Feedback Log",
            value=feedback_text,
            height=300,
            disabled=True,
            help="This log shows the decision-making process and review comments from the agents."
        )
        
        # 2. Portfolio Results
        final_portfolio = result.get("final_portfolio", {})
        
        if final_portfolio:
            st.markdown("### 📊 Approved Portfolio")
            
            # Prepare data for charts
            df_portfolio = pd.DataFrame(
                list(final_portfolio.items()), 
                columns=["Ticker", "Weight"]
            )
            df_portfolio["Percentage"] = (df_portfolio["Weight"] * 100).round(2)
            df_portfolio = df_portfolio.sort_values("Weight", ascending=False)
            
            col1, col2 = st.columns([1, 1])
            
            with col1:
                st.dataframe(
                    df_portfolio[["Ticker", "Percentage"]].style.format({"Percentage": "{:.2f}%"}),
                    use_container_width=True
                )
                
            with col2:
                fig = px.pie(
                    df_portfolio, 
                    values="Weight", 
                    names="Ticker", 
                    title="Portfolio Allocation",
                    hole=0.4
                )
                st.plotly_chart(fig, use_container_width=True)
                
            # Allocation Details
            allocation_results = result.get("allocation_results", [])
            if allocation_results:
                st.markdown("### 💰 Detailed Allocation")
                df_alloc = pd.DataFrame(allocation_results)
                st.dataframe(df_alloc, use_container_width=True)
                
                # Download Button
                csv = df_alloc.to_csv(index=False).encode('utf-8')
                st.download_button(
                    "📥 Download Allocation CSV",
                    csv,
                    "portfolio_allocation.csv",
                    "text/csv",
                    key='download-csv'
                )
        else:
            if st.session_state.job_status == "completed":
                st.warning("Analysis completed but no approved portfolio was generated.")
                st.info("The Reviewer Agent may have rejected the portfolio. Check the logs above advice.")
                
                st.markdown("---")
                st.markdown("#### ⚠️ Manual Override")
                st.write("If you disagree with the reviewer's assessment, you can force approval.")
                
                if st.button("✅ Override Review & Approve Portfolio", type="primary"):
                    with st.spinner("Authorizing and Calculating Allocation..."):
                        try:
                            resp = requests.post(f"{API_URL}/jobs/{st.session_state.job_id}/approve")
                            if resp.status_code == 200:
                                st.success("Portfolio approved! Refreshing...")
                                time.sleep(1)
                                st.rerun()
                            else:
                                st.error(f"Approval failed: {resp.text}")
                        except Exception as e:
                            st.error(f"Error communicating with API: {e}")
    
    elif st.session_state.job_status == "running":
        st.info(f"Job is running... ID: {st.session_state.job_id}")
    elif st.session_state.job_status == "failed":
         st.error("Job execution failed.")
