"""
LangGraph orchestration logic for the Multi-Agent SMA Customization Engine.

This module defines the agent workflow and state transitions using LangGraph.
It orchestrates multiple specialized agents that collaborate to customize
SMA portfolios, including data retrieval, risk analysis, optimization, and
recommendation generation.
"""

import numpy as np
import pandas as pd
import json
from typing import Dict
from langgraph.graph import StateGraph, END
from langchain_openai import ChatOpenAI
from langchain_core.prompts import ChatPromptTemplate
from dotenv import load_dotenv
from src.state import SMAState

# Load environment variables from .env file
load_dotenv()
from src.agents.mandate_agent import parse_mandate_node
from src.agents.optimizer_agent import generate_optimizer_code_node
from src.tools.fmp_client import FMPClient
from src.tools.executor import execute_optimizer_code


def data_fetcher_node(state: SMAState) -> Dict:
    """
    Node function to fetch market data from FMP API.
    
    Fetches S&P 500 universe, filters by constraints if needed,
    and retrieves historical prices for the universe.
    """
    try:
        # Initialize FMP client
        fmp_client = FMPClient()
        
        # Get S&P 500 universe
        sp500_companies = fmp_client.get_sp500_universe()
        
        # Extract tickers
        tickers = [company.get("symbol") for company in sp500_companies if company.get("symbol")]
        
        # Apply sector filtering if excluded_sectors are specified
        structured_constraints = state.get("structured_constraints", {})
        excluded_sectors = structured_constraints.get("excluded_sectors", [])
        
        if excluded_sectors:
            # Filter out excluded sectors
            filtered_companies = [
                company for company in sp500_companies
                if company.get("sector") not in excluded_sectors
            ]
            tickers = [company.get("symbol") for company in filtered_companies if company.get("symbol")]
        
        if not tickers:
            return {
                "universe": [],
                "market_data": pd.DataFrame(),
                "feedback": "No tickers available after applying constraints"
            }
        
        # Fetch historical prices (252 trading days = ~1 year)
        market_data = fmp_client.get_historical_prices(tickers, days=252)
        
        return {
            "universe": tickers,
            "market_data": market_data
        }
        
    except Exception as e:
        error_msg = f"Error fetching market data: {str(e)}"
        print(error_msg)
        return {
            "universe": [],
            "market_data": pd.DataFrame(),
            "feedback": error_msg
        }


def risk_model_node(state: SMAState) -> Dict:
    """
    Node function to calculate risk model from market data.
    
    Calculates expected returns (mu) and covariance matrix (Sigma)
    from historical price data.
    """
    market_data = state.get("market_data")
    
    if market_data is None or market_data.empty:
        return {
            "risk_model": {},
            "feedback": "No market data available for risk model calculation"
        }
    
    try:
        # Calculate returns from prices
        returns = market_data.pct_change().dropna()
        
        if returns.empty:
            return {
                "risk_model": {},
                "feedback": "Insufficient data to calculate returns"
            }
        
        # Calculate expected returns (mean of returns, annualized)
        mu = returns.mean().values * 252  # Annualize (252 trading days)
        
        # Calculate covariance matrix (annualized)
        Sigma = returns.cov().values * 252  # Annualize
        
        # Ensure mu is 1D and Sigma is 2D
        mu = np.asarray(mu).flatten()
        Sigma = np.asarray(Sigma)
        
        # Validate dimensions match
        if mu.shape[0] != Sigma.shape[0] or mu.shape[0] != Sigma.shape[1]:
            return {
                "risk_model": {},
                "feedback": f"Dimension mismatch: mu.shape={mu.shape}, Sigma.shape={Sigma.shape}"
            }
        
        # Convert to lists for JSON serialization (numpy arrays aren't JSON serializable)
        risk_model = {
            "mu": mu.tolist(),
            "Sigma": Sigma.tolist()
        }
        
        return {"risk_model": risk_model}
        
    except Exception as e:
        error_msg = f"Error calculating risk model: {str(e)}"
        print(error_msg)
        return {
            "risk_model": {},
            "feedback": error_msg
        }


def code_executor_node(state: SMAState) -> Dict:
    """
    Node function to execute generated optimizer code.
    
    Executes the Python code generated by the Optimizer Agent
    and extracts portfolio weights.
    """
    generated_python_code = state.get("generated_python_code", "")
    risk_model = state.get("risk_model", {})
    
    if not generated_python_code:
        return {"feedback": "No generated code to execute"}
    
    if not risk_model:
        return {"feedback": "No risk model available for code execution"}
    
    # Execute the code
    result = execute_optimizer_code(generated_python_code, risk_model)
    
    if "error" in result:
        # Execution failed - return error as feedback
        return {"feedback": result["error"]}
    
    # Execution succeeded - map weights to tickers
    weights = result.get("weights", {})
    universe = state.get("universe", [])
    
    # Map weights to tickers
    final_portfolio = {}
    for idx_str, weight in weights.items():
        idx = int(idx_str)
        if 0 <= idx < len(universe):
            ticker = universe[idx]
            final_portfolio[ticker] = weight
    
    return {"final_portfolio": final_portfolio}


def reviewer_agent_node(state: SMAState) -> Dict:
    """
    Node function for the Reviewer Agent.
    
    Reviews the final portfolio and provides approval or feedback
    based on the original constraints and mandate.
    """
    final_portfolio = state.get("final_portfolio", {})
    structured_constraints = state.get("structured_constraints", {})
    user_mandate = state.get("user_mandate", "")
    
    if not final_portfolio:
        return {
            "feedback": "No portfolio to review"
        }
    
    # Initialize OpenAI LLM
    llm = ChatOpenAI(model="gpt-4o-mini", temperature=0)
    
    # System prompt
    system_prompt = (
        "You are an expert Portfolio Reviewer. Review the generated portfolio "
        "against the original mandate and constraints. Provide a brief assessment "
        "and either approve or provide specific feedback for improvement."
    )
    
    # Create prompt template
    prompt = ChatPromptTemplate.from_messages([
        ("system", system_prompt),
        ("human", """Review the following portfolio:

User Mandate:
{user_mandate}

Constraints:
{constraints}

Final Portfolio:
{portfolio}

Provide your review. If the portfolio meets the requirements, respond with "APPROVED".
If not, provide specific feedback on what needs to be improved.""")
    ])
    
    # Create chain
    chain = prompt | llm
    
    try:
        constraints_str = json.dumps(structured_constraints, indent=2)
        portfolio_str = json.dumps(final_portfolio, indent=2)
        
        # Invoke the chain
        response = chain.invoke({
            "user_mandate": user_mandate,
            "constraints": constraints_str,
            "portfolio": portfolio_str
        })
        
        # Extract response
        review = response.content if hasattr(response, 'content') else str(response)
        review = review.strip()
        
        return {"feedback": review}
        
    except Exception as e:
        error_msg = f"Error in reviewer agent: {str(e)}"
        print(error_msg)
        return {"feedback": error_msg}


def should_retry_optimization(state: SMAState) -> str:
    """
    Conditional function to determine if optimization should be retried.
    
    Checks if there's an error in feedback (from code execution).
    If error exists, route back to OptimizerAgent. Otherwise, proceed to ReviewerAgent.
    """
    feedback = state.get("feedback", "")
    if feedback and "error" in feedback.lower():
        return "retry"
    return "review"


def should_end(state: SMAState) -> str:
    """
    Conditional function to determine if workflow should end.
    
    Checks if portfolio is approved by reviewer based on feedback.
    """
    feedback = state.get("feedback", "")
    # Check if feedback indicates approval
    if feedback and "approved" in feedback.lower():
        return "end"
    return "continue"


def create_workflow() -> StateGraph:
    """
    Create and configure the LangGraph workflow for SMA customization.
    
    Returns:
        Compiled StateGraph ready for execution
    """
    # Create the workflow graph
    workflow = StateGraph(SMAState)
    
    # Add nodes
    workflow.add_node("parse_mandate", parse_mandate_node)
    workflow.add_node("fetch_data", data_fetcher_node)
    workflow.add_node("calculate_risk_model", risk_model_node)
    workflow.add_node("generate_optimizer_code", generate_optimizer_code_node)
    workflow.add_node("execute_code", code_executor_node)
    workflow.add_node("review_portfolio", reviewer_agent_node)
    
    # Define the workflow edges
    # Start -> MandateAgent
    workflow.set_entry_point("parse_mandate")
    
    # MandateAgent -> DataFetcherNode
    workflow.add_edge("parse_mandate", "fetch_data")
    
    # DataFetcherNode -> RiskModelNode
    workflow.add_edge("fetch_data", "calculate_risk_model")
    
    # RiskModelNode -> OptimizerAgent
    workflow.add_edge("calculate_risk_model", "generate_optimizer_code")
    
    # OptimizerAgent -> CodeExecutorNode
    workflow.add_edge("generate_optimizer_code", "execute_code")
    
    # CodeExecutorNode -> Conditional edge
    workflow.add_conditional_edges(
        "execute_code",
        should_retry_optimization,
        {
            "retry": "generate_optimizer_code",  # Go back to OptimizerAgent if error
            "review": "review_portfolio"  # Go to ReviewerAgent if success
        }
    )
    
    # ReviewerAgent -> Conditional edge
    workflow.add_conditional_edges(
        "review_portfolio",
        should_end,
        {
            "end": END,  # End if approved
            "continue": END  # End even if not approved (could be changed to retry)
        }
    )
    
    return workflow.compile()


# Create the compiled app
app = create_workflow()
