"""
LangGraph orchestration logic for the Multi-Agent SMA Customization Engine.

This module defines the agent workflow and state transitions using LangGraph.
It orchestrates multiple specialized agents that collaborate to customize
SMA portfolios, including data retrieval, risk analysis, optimization, and
recommendation generation.
"""

import numpy as np
import pandas as pd
import json
from typing import Dict
from langgraph.graph import StateGraph, END
from langchain_openai import ChatOpenAI
from langchain_core.prompts import ChatPromptTemplate
from dotenv import load_dotenv
import sys
from pathlib import Path

# Add project root to Python path to allow imports when running directly
project_root = Path(__file__).parent.parent
if str(project_root) not in sys.path:
    sys.path.insert(0, str(project_root))

from src.state import SMAState

# Load environment variables from .env file
load_dotenv()
from src.agents.mandate_agent import parse_mandate_node
from src.agents.finviz_screener_agent import finviz_screener_node
from src.agents.pricing_agent import pricing_agent_node
from src.agents.optimizer_agent import generate_optimizer_code_node
from src.tools.executor import execute_optimizer_code
from src.agents.allocation_agent import allocation_agent_node


def risk_model_node(state: SMAState) -> Dict:
    """
    Node function to calculate risk model from market data.
    
    Calculates expected returns (mu) and covariance matrix (Sigma)
    from historical price data.
    """
    market_data = state.get("market_data")
    
    if market_data is None or market_data.empty:
        return {
            "risk_model": {},
            "feedback": ["No market data available for risk model calculation"]
        }
    
    try:
        # Handle missing data more robustly
        # 1. Fill missing values (forward fill then backward fill)
        filled_data = market_data.ffill().bfill()
        
        # 2. Drop columns (tickers) that still have any NaNs (these have no data at all)
        initial_tickers = filled_data.columns.tolist()
        clean_data = filled_data.dropna(axis=1)
        remaining_tickers = clean_data.columns.tolist()
        
        if len(remaining_tickers) < len(initial_tickers):
            dropped = list(set(initial_tickers) - set(remaining_tickers))
            print(f"⚠️ Dropped {len(dropped)} tickers due to missing data: {dropped[:5]}...")

        # Calculate returns from prices
        returns = clean_data.pct_change()
        # Drop the first row as it will be NaN after pct_change
        returns = returns.dropna(axis=0, how='all')
        
        if returns.empty:
            return {
                "risk_model": {},
                "feedback": ["Insufficient data to calculate returns after cleaning"]
            }
        
        # Calculate expected returns (mean of returns, annualized)
        mu = returns.mean().values * 252  # Annualize (252 trading days)
        
        # Calculate covariance matrix (annualized)
        Sigma = returns.cov().values * 252  # Annualize
        
        # Ensure mu is 1D and Sigma is 2D
        mu = np.asarray(mu).flatten()
        Sigma = np.asarray(Sigma)
        
        # Check for any remaining NaNs in mu or Sigma
        if np.isnan(mu).any() or np.isnan(Sigma).any():
            return {
                "risk_model": {},
                "feedback": ["Calculated risk model contains NaN values"]
            }

        # Validate dimensions match
        if mu.shape[0] != Sigma.shape[0] or mu.shape[0] != Sigma.shape[1]:
            return {
                "risk_model": {},
                "feedback": [f"Dimension mismatch: mu.shape={mu.shape}, Sigma.shape={Sigma.shape}"]
            }
        
        # Convert to lists for JSON serialization
        risk_model = {
            "mu": mu.tolist(),
            "Sigma": Sigma.tolist(),
            "tickers": remaining_tickers  # Store synchronized tickers
        }
        
        print(f"✅ Risk model calculated for {len(remaining_tickers)} assets")
        return {
            "risk_model": risk_model,
            "universe": remaining_tickers # Update universe to match risk model
        }
        
    except Exception as e:
        error_msg = f"Error calculating risk model: {str(e)}"
        print(error_msg)
        return {
            "risk_model": {},
            "feedback": [error_msg]
        }


def code_executor_node(state: SMAState) -> Dict:
    """
    Node function to execute generated optimizer code.
    
    Executes the Python code generated by the Optimizer Agent
    and extracts portfolio weights.
    """
    generated_python_code = state.get("generated_python_code", "")
    risk_model = state.get("risk_model", {})
    
    if not generated_python_code:
        return {"feedback": ["No generated code to execute"]}
    
    if generated_python_code.startswith("# Error"):
        # This is a real generation error from the agent
        return {"feedback": [f"Optimizer Agent encountered an issue: {generated_python_code}"]}

    if not risk_model:
        return {"feedback": ["No risk model available for code execution"]}
    
    print("⚙️ Executing optimization code...")
    # Execute the code
    result = execute_optimizer_code(generated_python_code, risk_model)
    
    if "error" in result:
        # Execution failed - return error as feedback
        print(f"❌ Optimization execution failed: {result['error']}")
        return {"feedback": [f"Optimization Error: {result['error']}"]}
    
    # Execution succeeded - map weights to tickers
    weights = result.get("weights", {})
    universe = state.get("universe", [])
    
    if not weights:
        return {"feedback": ["Optimization returned empty weights"]}

    # Map weights to tickers
    final_portfolio = {}
    for idx_str, weight in weights.items():
        try:
            idx = int(idx_str)
            if 0 <= idx < len(universe):
                ticker = universe[idx]
                if weight > 1e-6: # Only include non-zero weights
                    final_portfolio[ticker] = weight
        except (ValueError, TypeError):
            continue
    
    feedback_msgs = ["Optimization successful. Weights calculated."]
    
    # Save optimization model description if available
    if "problem_description" in result:
        try:
            with open("optimization_model.txt", "w") as f:
                f.write(result["problem_description"])
            feedback_msgs.append("Optimization model saved to optimization_model.txt for validation.")
            print("📄 Optimization model saved to optimization_model.txt")
        except Exception as e:
            print(f"⚠️ Failed to save optimization model: {e}")

    print(f"✅ Optimization successful. Generated portfolio with {len(final_portfolio)} assets.")
    return {
        "final_portfolio": final_portfolio, 
        "feedback": feedback_msgs
    }


def reviewer_agent_node(state: SMAState) -> Dict:
    """
    Node function for the Reviewer Agent.
    """
    final_portfolio = state.get("final_portfolio", {})
    structured_constraints = state.get("structured_constraints", {})
    user_mandate = state.get("user_mandate", "")
    
    if not final_portfolio:
        return {"feedback": ["No portfolio to review"]}
    
    # Initialize OpenAI LLM - Upgrade to gpt-4o
    llm = ChatOpenAI(model="gpt-4o", temperature=0)
    
    # System prompt
    system_prompt = (
        "You are an expert Portfolio Reviewer. Critically assess the generated portfolio "
        "against the original mandate and constraints. Provide a technical assessment "
        "and either approve or provide specific feedback for improvement."
    )
    
    # Create prompt template
    prompt = ChatPromptTemplate.from_messages([
        ("system", system_prompt),
        ("human", """Review the following portfolio construction:

User Mandate: {user_mandate}
Constraints: {constraints}
Final Portfolio: {portfolio}

Provide your review. If the portfolio meets the requirements, end your response with "APPROVED".
Otherwise, provide specific feedback on what needs to be improved.""")
    ])
    
    # Create chain
    chain = prompt | llm
    
    try:
        constraints_str = json.dumps(structured_constraints, indent=2)
        portfolio_str = json.dumps(final_portfolio, indent=2)
        
        # Invoke the chain
        response = chain.invoke({
            "user_mandate": user_mandate,
            "constraints": constraints_str,
            "portfolio": portfolio_str
        })
        
        # Extract response
        review = response.content if hasattr(response, 'content') else str(response)
        review = review.strip()
        
        # Check for automatic approval
        if "APPROVED" in review:
            return {"feedback": [f"Reviewer assessment: {review}"]}
            
        # Interactive Manual Override
        # Only allow override if running interactively (CLI)
        is_interactive = state.get("is_interactive", True)
        
        if is_interactive:
            print("\n" + "!"*80)
            print("⚠️  The Reviewer Agent has concerns about the portfolio:")
            print("-" * 80)
            print(review)
            print("-" * 80)
            print("Do you want to OVERRIDE this assessment and proceed to allocation? (Y/N)")
            
            override = input("Override? > ").strip().lower()
            
            if override in ['y', 'yes', 'true', '1']:
                print("✅ User manually APPROVED the portfolio.")
                timestamped_feedback = f"Reviewer assessment: {review}"
                return {"feedback": [timestamped_feedback, "APPROVED by User Override"]}
            else:
                print("❌ User rejected the portfolio.")
                return {"feedback": [f"Reviewer assessment: {review}", "REJECTED by User"]}
        else:
             # In API/Non-interactive mode, strictly follow Reviewer
             return {"feedback": [f"Reviewer assessment: {review}"]}
        
    except Exception as e:
        error_msg = f"Error in reviewer agent: {str(e)}"
        print(error_msg)
        return {"feedback": [error_msg]}


def should_retry_optimization(state: SMAState) -> str:
    """
    Conditional function to determine if optimization should be retried.
    Limits retries to 3 to prevent infinite loops.
    """
    retry_count = state.get("optimization_retry_count", 0)
    
    # Check if we've exceeded the limit
    if retry_count >= 3:
        print(f"⚠️ Optimization retry limit reached ({retry_count}). Proceeding to review.")
        return "review"

    # Look at the last message in feedback
    feedback_list = state.get("feedback", [])
    last_feedback = feedback_list[-1].lower() if feedback_list else ""
    
    final_portfolio = state.get("final_portfolio", {})
    
    if not final_portfolio:
        # If the failure is due to missing data (Risk Model), don't retry - it won't help.
        if "missing risk model" in last_feedback or "no risk model" in last_feedback:
            print("🚫 Missing data identified. Skipping retry.")
            return "review"
            
        if any(kw in last_feedback for kw in ["error", "fail", "incomplete"]):
            # Only retry if it's a code/logic issue that the LLM might fix
            if any(term in last_feedback for term in ["code", "syntax", "solver", "infeasible", "dcp"]):
                print(f"🔄 Retrying optimization (Total attempts so far: {retry_count})...")
                return "retry"
    
    return "review"


def should_end(state: SMAState) -> str:
    """
    Conditional function to determine if workflow should end.
    """
    feedback_list = state.get("feedback", [])
    last_feedback = feedback_list[-1].lower() if feedback_list else ""
    
    if "approved" in last_feedback:
        # Check for negation
        if "not approved" in last_feedback:
            # Continue to END (Rejected)
            print(f"\n🛑 Portfolio NOT APPROVED by Reviewer (Status: '{last_feedback[:100]}...'). Workflow ending.")
            return "continue"
            
        if "override" in last_feedback:
            print("\n✅ Portfolio Manually APPROVED by User. Proceeding to Allocation Agent.")
        else:
            print("\n✅ Portfolio APPROVED by Reviewer. Proceeding to Allocation Agent.")
        return "end"
    
    print(f"\n🛑 Portfolio NOT APPROVED by Reviewer (Status: '{last_feedback[:100]}...'). Workflow ending.")
    return "continue"


def create_workflow() -> StateGraph:
    """
    Create and configure the LangGraph workflow for SMA customization.
    
    Returns:
        Compiled StateGraph ready for execution
    """
    # Create the workflow graph
    workflow = StateGraph(SMAState)
    
    # Add nodes
    workflow.add_node("parse_mandate", parse_mandate_node)
    workflow.add_node("screen_stocks", finviz_screener_node)
    workflow.add_node("fetch_prices", pricing_agent_node)
    workflow.add_node("calculate_risk_model", risk_model_node)
    workflow.add_node("generate_optimizer_code", generate_optimizer_code_node)
    workflow.add_node("execute_code", code_executor_node)
    workflow.add_node("review_portfolio", reviewer_agent_node)
    workflow.add_node("allocate_funds", allocation_agent_node)
    
    # Define the workflow edges
    # Start -> MandateAgent
    workflow.set_entry_point("parse_mandate")
    
    # MandateAgent -> FinvizScreenerNode
    workflow.add_edge("parse_mandate", "screen_stocks")
    
    # FinvizScreenerNode -> PricingAgentNode
    workflow.add_edge("screen_stocks", "fetch_prices")
    
    # PricingAgentNode -> RiskModelNode
    workflow.add_edge("fetch_prices", "calculate_risk_model")
    
    # RiskModelNode -> OptimizerAgent
    workflow.add_edge("calculate_risk_model", "generate_optimizer_code")
    
    # OptimizerAgent -> CodeExecutorNode
    workflow.add_edge("generate_optimizer_code", "execute_code")
    
    # CodeExecutorNode -> Conditional edge
    workflow.add_conditional_edges(
        "execute_code",
        should_retry_optimization,
        {
            "retry": "generate_optimizer_code",  # Go back to OptimizerAgent if error
            "review": "review_portfolio"  # Go to ReviewerAgent if success
        }
    )
    
    # ReviewerAgent -> Conditional edge
    workflow.add_conditional_edges(
        "review_portfolio",
        should_end,
        {
            "end": "allocate_funds",  # Go to Allocation if approved
            "continue": END  # End if not approved
        }
    )
    
    # AllocationAgent -> End
    workflow.add_edge("allocate_funds", END)
    
    return workflow.compile()


# Create the compiled app
app = create_workflow()


def visualize_graph():
    """
    Visualizes the application graph. 
    Intended for use in Jupyter/IPython environments.
    """
    try:
        from IPython.display import Image, display
        display(Image(app.get_graph().draw_mermaid_png()))
    except ImportError:
        print("IPython library not found. Please install ipython to visualize the graph.")
    except Exception as e:
        print(f"Could not visualize graph: {e}")


if __name__ == "__main__":
    # If run directly, try to save the graph image instead of displaying
    try:
        print("Generating graph visualization...")
        img_bytes = app.get_graph().draw_mermaid_png()
        output_file = "workflow_graph.png"
        with open(output_file, "wb") as f:
            f.write(img_bytes)
        print(f"Graph saved to {output_file}")
    except Exception as e:
        print(f"Graph visualization failed: {e}")
