"""
Safe code execution utility for the Multi-Agent SMA Customization Engine.

This module provides a secure way to execute generated Python code in an isolated
namespace with pre-injected dependencies (cvxpy, numpy, risk model data).
"""

import numpy as np
import cvxpy as cp
from typing import Dict, Union, Any
from cvxpy.error import SolverError


def execute_optimizer_code(
    generated_python_code: str,
    risk_model: Dict[str, Any]
) -> Dict[str, Union[Dict[str, float], str]]:
    """
    Safely execute generated Python code for portfolio optimization.
    
    Creates an isolated execution namespace, injects required dependencies,
    executes the code, and extracts the portfolio weights.
    
    Args:
        generated_python_code: Python code string generated by the Optimizer Agent
        risk_model: Dictionary containing 'mu' (expected returns) and 'Sigma' (covariance matrix)
        
    Returns:
        Dictionary with either:
        - 'weights': Dictionary mapping ticker indices/names to weights (float values)
        - 'error': Error message string if execution fails
    """
    if not generated_python_code or not generated_python_code.strip():
        return {"error": "No code provided for execution"}
    
    if not risk_model:
        return {"error": "No risk model data provided"}
    
    # Extract mu and Sigma from risk_model
    mu = risk_model.get("mu")
    Sigma = risk_model.get("Sigma")
    
    if mu is None or Sigma is None:
        return {"error": "Risk model missing 'mu' (expected returns) or 'Sigma' (covariance matrix)"}
    
    # Ensure mu and Sigma are numpy arrays
    try:
        mu = np.asarray(mu)
        Sigma = np.asarray(Sigma)
    except Exception as e:
        return {"error": f"Failed to convert risk model data to numpy arrays: {e}"}
    
    # Validate dimensions
    if mu.ndim != 1:
        return {"error": f"Expected mu to be 1D array, got {mu.ndim}D"}
    if Sigma.ndim != 2:
        return {"error": f"Expected Sigma to be 2D array, got {Sigma.ndim}D"}
    if mu.shape[0] != Sigma.shape[0] or mu.shape[0] != Sigma.shape[1]:
        return {"error": f"Dimension mismatch: mu.shape={mu.shape}, Sigma.shape={Sigma.shape}"}
    
    # Create isolated execution namespace
    local_namespace = {}
    
    # Inject required dependencies
    local_namespace['np'] = np
    local_namespace['numpy'] = np
    local_namespace['cvxpy'] = cp
    local_namespace['cp'] = cp
    local_namespace['mu'] = mu
    local_namespace['Sigma'] = Sigma
    
    try:
        # Execute the generated code in the isolated namespace
        exec(generated_python_code, {"__builtins__": __builtins__}, local_namespace)
        
    except SyntaxError as e:
        error_msg = f"Syntax error in generated code: {e.msg} at line {e.lineno}"
        if e.text:
            error_msg += f"\nCode: {e.text.strip()}"
        return {"error": error_msg}
    
    except SolverError as e:
        error_msg = f"CVXPY solver error: {str(e)}"
        return {"error": error_msg}
    
    except Exception as e:
        error_msg = f"Error executing code: {type(e).__name__}: {str(e)}"
        return {"error": error_msg}
    
    # Extract weights from the namespace
    if 'weights' not in local_namespace:
        return {"error": "Code executed successfully but 'weights' variable not found in namespace"}
    
    weights = local_namespace['weights']
    
    # Extract problem definition if available
    problem_description = ""
    if 'problem' in local_namespace:
        try:
            prob = local_namespace['problem']
            if isinstance(prob, cp.Problem):
                problem_description = str(prob)
        except Exception:
            pass

    # Inspect problem status if available
    if 'problem' in local_namespace:
        try:
            prob = local_namespace['problem']
            if isinstance(prob, cp.Problem):
                problem_description = str(prob)
                if prob.status not in ["optimal", "optimal_inaccurate"]:
                    return {
                        "error": f"Optimization solver failed. Status: {prob.status}. Weights are not available."
                    }
        except Exception:
            pass

    if weights is None:
        return {
            "error": "Optimization variable 'weights' is None. The solver likely failed to find a solution (Infeasible or Unbounded)."
        }

    # Convert weights to appropriate format
    try:
        # If weights is a numpy array, convert to list/dict
        if isinstance(weights, np.ndarray):
            weights = weights.flatten()  # Ensure 1D
            
            # Convert to dictionary with indices as keys
            # Handle potential None/NaN in array if any
            weights_list = []
            for w in weights:
                if w is None or (isinstance(w, float) and np.isnan(w)):
                    weights_list.append(0.0)
                else:
                    weights_list.append(float(w))
                    
            weights_dict = {str(i): w for i, w in enumerate(weights_list)}

        elif isinstance(weights, (list, tuple)):
            # Convert list/tuple to dictionary
            weights_dict = {}
            for i, w in enumerate(weights):
                if w is None:
                    weights_dict[str(i)] = 0.0
                else:
                    weights_dict[str(i)] = float(w)

        elif isinstance(weights, dict):
            # Already a dictionary, ensure values are floats
            weights_dict = {}
            for k, v in weights.items():
                if v is None:
                    weights_dict[str(k)] = 0.0
                else:
                    weights_dict[str(k)] = float(v)
        else:
            # Try to convert to float if single value
            weights_dict = {"0": float(weights)}
        
        # Validate weights sum to approximately 1.0 (allow small floating point errors)
        total_weight = sum(weights_dict.values())
        
        # Check if total weight is effectively zero (failed opt)
        if total_weight < 1e-6:
             return {
                "error": f"Total portfolio weight is practically zero ({total_weight}). Optimization likely failed to allocate capital."
            }

        if abs(total_weight - 1.0) > 0.01:  # Allow 1% tolerance
            return {
                "error": f"Weights do not sum to 1.0 (sum={total_weight:.6f}). "
                        f"This may indicate an optimization problem."
            }
        
        # Validate all weights are non-negative
        if any(w < -1e-6 for w in weights_dict.values()):  # Allow small negative due to numerical errors
            return {
                "error": "Some weights are negative. Portfolio weights must be non-negative."
            }
        
        result = {"weights": weights_dict}
        if problem_description:
            result["problem_description"] = problem_description
        return result
        
    except (ValueError, TypeError) as e:
        return {"error": f"Failed to convert weights to dictionary: {e}"}

